"use client"
import "./globals.css";
import { CiUser } from "react-icons/ci";
import { PiHeartStraightLight } from "react-icons/pi";
import { HiOutlineShoppingBag } from "react-icons/hi2";
import { TbH4, TbMenu } from "react-icons/tb";
import Hilogo from '../app/assets/img/h4-logo-x2.webp'
import Image from "next/image";
import { HiMenuAlt4 } from "react-icons/hi";
import localFont from 'next/font/local'
import useStore from "../app/store";
import { IoCloseOutline } from "react-icons/io5";
import { useEffect } from "react";
import Link from "next/link";




// export const metadata = {
//   title: "vegan chocolate",
//   description: "Generated by create next app",
//   icons: {
//     icon: [
//       {
//         media: '(prefers-color-scheme: light)',
//         url: '/logo.ico',
//         href: '/logo.ico',
//       },
//     ],
//   },
// };

const myFont = localFont({
  src: "./assets/font/Marcellus-Regular.ttf",
  display: "swap",
});

const font2 = localFont({
  src: "./assets/font/DancingScript-Regular.ttf",
  display: "swap",

})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.ico" sizes="any" />
      </head>
      <body className={myFont.className}>
        <MyHeader></MyHeader>
        {children}
      </body>
    </html>
  );
}


function MyHeader() {
  const cartState = useStore((state) => state);
  if (!cartState) {
    return null
  }
  const { cart, removeFromCart } = cartState;



  let totalprice
  function calculat_total(cart) {
    totalprice = 0
    for (let i = 0; i < cart.length; i++) {
      totalprice += cart[i].price
    }
    return (totalprice)

  }
  return (
    <header className=" w-full relative ">
      <section className=" w-full flex  justify-evenly px-10 py-8">
        <section className=" hidden lg:flex w-[40%]">
          <nav className=" w-full ">
            <ul className=" w-full flex text-[#d1b17b] uppercase text-sm *:mx-5 cursor-pointer ">
              <li>home</li>
              <li>pages</li>
              <li>shop</li>
              <li>blog</li>
              <li>gallery</li>

            </ul>
          </nav>
        </section>
        <section className=" w-full flex lg:justify-center justify-star  ">
          <figure>
            <Image className=" lg:w-[80px] w-[50px]" src={Hilogo}></Image>
          </figure>
        </section>
        <section className=" hidden lg:flex w-[40%]">
          <nav className=" w-full flex justify-end">
            <ul className=" w-full flex justify-end text-[#d1b17b] uppercase text-xl *:mx-5">
              <li><CiUser></CiUser></li>
              <li><PiHeartStraightLight></PiHeartStraightLight></li>
              <li className=" relative hov flex cursor-pointer ">
                <HiOutlineShoppingBag></HiOutlineShoppingBag>
                <li className="text-xs">{cart.length}</li>
                <div className="absolute  mymenu w-[300px] h-[500px] bg-white -right-2 top-10  p-4 overflow-hidden  ">
                  <div className=" h-[80%] w-full  overflow-y-scroll myscroll">
                    <ul className=" w-full ">
                      <li className=" relative  *:my-4">
                        {cart && cart.map((val) => {
                          return (
                            <li className=" flex *:w-1/3 justify-between content-start ">
                              <figure>
                                <Image width={1000} height={1000} className=" w-[80px]" src={val.avatar} alt="" />
                              </figure>
                              <div className=" *:w-full flex flex-wrap  ">
                                <span className=" text-black text-sm ">{val.name}</span>
                                <span className=" text-gray-600 text-sm">${val.price}.00</span>
                              </div>
                              <span className=" text-black flex justify-end pe-2 cursor-pointer">
                                <IoCloseOutline onClick={() => removeFromCart(val.id)}></IoCloseOutline>
                              </span>
                            </li>
                          )
                        })}
                      </li>
                    </ul>
                  </div>
                  <div className=" absolute  w-full bottom-0 left-0 h-[20%] text-[#63605a] p-2">
                    <div className="text-sm  flex *:w-1/2  justify-between">
                      <span>Total:</span>
                      <span className=" flex justify-end">${calculat_total(cart)}.00</span>
                    </div>
                    <div className=" py-2">
                      <span className=" flex justify-center text-sm border border-[#A78957] py-2 text-[#A78957] cursor-pointer">
                        <Link href={'/assets/row/checkout'}>check out</Link>
                      </span>
                    </div>
                  </div>
                </div>
              </li>
              <li><TbMenu></TbMenu></li>
            </ul>
          </nav>
        </section>
        <section className=" w-1/2 flex justify-end lg:hidden">
          <HiMenuAlt4 className=" text-4xl text-[#d1b17b]"></HiMenuAlt4>
        </section>
      </section>
    </header>
  )
}